'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :4.0.30319.42000
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    'à l'aide d'un outil, tel que ResGen ou Visual Studio.
    'Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    'avec l'option /str ou régénérez votre projet VS.
    '''<summary>
    '''  Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ChaBug.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Remplace la propriété CurrentUICulture du thread actuel pour toutes
        '''  les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property background() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("background", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property backgroundBugged() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("backgroundBugged", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bullet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bullet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.IO.UnmanagedMemoryStream semblable à System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property bullet_sound1() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("bullet_sound1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.IO.UnmanagedMemoryStream semblable à System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property bullet_sound2() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("bullet_sound2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.IO.UnmanagedMemoryStream semblable à System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property bullet_sound3() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("bullet_sound3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bulletBugged() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bulletBugged", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.IO.UnmanagedMemoryStream semblable à System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property cf_bullet1() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("cf_bullet1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.IO.UnmanagedMemoryStream semblable à System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property cf_bullet2() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("cf_bullet2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.IO.UnmanagedMemoryStream semblable à System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property cf_bullet3() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("cf_bullet3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.IO.UnmanagedMemoryStream semblable à System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property cf_death1() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("cf_death1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.IO.UnmanagedMemoryStream semblable à System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property cf_death2() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("cf_death2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.IO.UnmanagedMemoryStream semblable à System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property cf_death3() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("cf_death3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.IO.UnmanagedMemoryStream semblable à System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property cf_hurt1() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("cf_hurt1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.IO.UnmanagedMemoryStream semblable à System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property cf_hurt2() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("cf_hurt2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.IO.UnmanagedMemoryStream semblable à System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property cf_hurt3() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("cf_hurt3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property characterAnimationSheet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("characterAnimationSheet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property characterAnimationSheetBugged() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("characterAnimationSheetBugged", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.IO.UnmanagedMemoryStream semblable à System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property close_explorer() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("close_explorer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cooldownBar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cooldownBar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cooldownFrame() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cooldownFrame", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cooldownFrameFull() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cooldownFrameFull", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property corruptedFile() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("corruptedFile", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property corruptedFileBullet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("corruptedFileBullet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.IO.UnmanagedMemoryStream semblable à System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property death() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("death", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property directory() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("directory", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.IO.UnmanagedMemoryStream semblable à System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property end_of_tableau() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("end_of_tableau", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.IO.UnmanagedMemoryStream semblable à System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property enemy_death1() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("enemy_death1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.IO.UnmanagedMemoryStream semblable à System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property enemy_death2() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("enemy_death2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property enemySheet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("enemySheet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.IO.UnmanagedMemoryStream semblable à System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property enter_dir() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("enter_dir", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fileType_configtxt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fileType_configtxt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fileType_image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fileType_image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fileType_void() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fileType_void", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property health() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("health", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HealthBarFrameCorruptedFile() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HealthBarFrameCorruptedFile", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.IO.UnmanagedMemoryStream semblable à System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property hurt1() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("hurt1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.IO.UnmanagedMemoryStream semblable à System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property hurt2() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("hurt2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.IO.UnmanagedMemoryStream semblable à System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property hurt3() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("hurt3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.IO.UnmanagedMemoryStream semblable à System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property hurt4() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("hurt4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.IO.UnmanagedMemoryStream semblable à System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property jump1() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("jump1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.IO.UnmanagedMemoryStream semblable à System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property jump2() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("jump2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à {&quot;Character&quot;:{&quot;Acceleration&quot;:{&quot;X&quot;:0,&quot;Y&quot;:0},&quot;Cooldown&quot;:0,&quot;Height&quot;:24,&quot;InitialCooldown&quot;:0,&quot;Input&quot;:false,&quot;IsAirborne&quot;:false,&quot;Location&quot;:{&quot;X&quot;:10,&quot;Y&quot;:630},&quot;Velocity&quot;:{&quot;X&quot;:0,&quot;Y&quot;:0},&quot;Width&quot;:24,&quot;gravityAcceleration&quot;:{&quot;X&quot;:0,&quot;Y&quot;:5.5},&quot;inherentAcceleration&quot;:{&quot;X&quot;:0,&quot;Y&quot;:0},&quot;isLookingLeft&quot;:false,&quot;steppingPlatform&quot;:null,&quot;touchingWall&quot;:null},&quot;GroundHeight&quot;:632,&quot;HUD&quot;:null,&quot;TextureObjectsList&quot;:[{&quot;BackgroundImage&quot;:null,&quot;BackgroundImageName&quot;:&quot;tuto0&quot;,&quot;Location&quot;:{&quot;IsEmpty&quot;:false,&quot;X&quot;:440,&quot;Y&quot;:150},&quot;Size&quot;:{&quot;Height&quot;:55,&quot;IsEmpty&quot;:fals [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property levels() As String
            Get
                Return ResourceManager.GetString("levels", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.IO.UnmanagedMemoryStream semblable à System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property music() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("music", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.IO.UnmanagedMemoryStream semblable à System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property solve_bug() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("solve_bug", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property textureObjectType_end() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("textureObjectType_end", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property textureObjectType_explorerBackground() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("textureObjectType_explorerBackground", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property textureObjectType_tuto0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("textureObjectType_tuto0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property textureObjectType_tuto1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("textureObjectType_tuto1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property textureObjectType_tuto2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("textureObjectType_tuto2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property textureObjectType_tuto3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("textureObjectType_tuto3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property textureObjectType_tuto4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("textureObjectType_tuto4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Timeless() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Timeless", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.IO.UnmanagedMemoryStream semblable à System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property walk_explorer() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("walk_explorer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.IO.UnmanagedMemoryStream semblable à System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property walk_normal() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("walk_normal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property wallTiles() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wallTiles", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
